spec:
  destination:
    server: https://d1683604-ad9d-488f-bf90-05d1949b9312.ap-south-1.linodelke.net:443
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
